[phases.setup]
nixpkgs = ["pkgs.mesa", "pkgs.libXext", "pkgs.libSM"]

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install torch==2.5.1 torchvision==0.20.1 --index-url https://download.pytorch.org/whl/cu121',
  'pip install -r requirements.txt'
]

[start]
cmd = 'python cheetah_detector_app.py'

